apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/autodmca-backend-role"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-service-account
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/autodmca-worker-role"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beat-service-account
  namespace: production
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/autodmca-scheduler-role"
automountServiceAccountToken: true
---
# Role for backend pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: production
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: production
subjects:
- kind: ServiceAccount
  name: backend-service-account
  namespace: production
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
---
# Role for worker pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: worker-role
  namespace: production
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-rolebinding
  namespace: production
subjects:
- kind: ServiceAccount
  name: worker-service-account
  namespace: production
roleRef:
  kind: Role
  name: worker-role
  apiGroup: rbac.authorization.k8s.io
---
# Role for beat scheduler pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: beat-role
  namespace: production
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: beat-rolebinding
  namespace: production
subjects:
- kind: ServiceAccount
  name: beat-service-account
  namespace: production
roleRef:
  kind: Role
  name: beat-role
  apiGroup: rbac.authorization.k8s.io